#!/bin/sh /etc/rc.common
START=94
USE_PROCD=1
start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/allowed-presence.sh
  procd_set_param respawn 2000 5 5
  procd_close_instance
}
